on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
name: Release
jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.target-suffix }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, aarch64]
        include:
          - os: ubuntu-latest
            target-suffix: unknown-linux-gnu
          - os: macos-latest
            target-suffix: apple-darwin
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # ratchet:actions/checkout@v6
      - uses: cashapp/activate-hermit@e49f5cb4dd64ff0b0b659d1d8df499595451155a # ratchet:cashapp/activate-hermit@v1
        with:
          cache: true
      - id: build
        shell: bash
        run: |
          export TARGET="${{ matrix.arch }}-${{ matrix.target-suffix }}"
          rustup target add "${TARGET}"
          cross build --release --target "${TARGET}"
          export TARGET_PATH="target/${TARGET}/release/t-${TARGET}"
          mv "target/${TARGET}"/release/t "${TARGET_PATH}"
          bzip2 -f9 "${TARGET_PATH}"
          echo "TARGET_PATH=${TARGET_PATH}.bz2" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # ratchet:actions/upload-artifact@v6
        with:
          name: t-${{ matrix.arch }}-${{ matrix.target-suffix }}
          path: ${{ steps.build.outputs.TARGET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # ratchet:actions/download-artifact@v7
        with:
          merge-multiple: true
      - uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # ratchet:ncipollo/release-action@v1
        with:
          artifacts: "t-*.bz2"
          generateReleaseNotes: true
